apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  namespace: webapp
spec:
  type: NodePort
  ports:
  - name: "db-service"
    port: 3306
    targetPort: 3306
  selector:
    app: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: NNYp9XM4zkDnZvn5
        ports:
        - containerPort: 32048
          name: mysql