apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web-service
  namespace: webapp
spec:
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 81
    targetPort: 5000
  selector:
    app: web
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: webapp
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: python-api
        image: harsh19shetty/webapp_47
        ports:
        - containerPort: 5000